version: '3.8'

services:
  api_gateway:
    build:
      context: ./APIGateway
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - emotion_detection 

  emotion_detection:
    build:
      context: ./EmotionDetection
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
